AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  PermissionSetName:
    Type: String
  Description:
    Type: String
  InstanceArn:
    Type: String
  InlinePolicyDocument:
    Type: String
  SessionDuration:
    Type: String
    Default: PT8H
  ManagedPolicies:
    Type: String
    Default: ""

Resources:
  PermissionSet:
    Type: AWS::SSO::PermissionSet
    Properties:
      Name: !Ref PermissionSetName
      Description: !Ref Description
      InstanceArn: !Ref InstanceArn
      SessionDuration: !Ref SessionDuration
      InlinePolicy: !Ref InlinePolicyDocument
      ManagedPolicies: !Ref ManagedPolicies